# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: 016973021151.dkr.ecr.us-east-1.amazonaws.com/cloudpocstation/micro-db
  tag: 1.0.7
  pullPolicy: IfNotPresent

database:
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  postgresqlDatabase: my-database